Repository UMC-7th-A1Grade/BackEnd, pull requests merged in 2025-02, with the labels that each got.

#56 ✨ FEAT: 문제 이미지 업로드 기능 구현
  src/main/java/com/umc7th/a1grade/domain/question/controller/QuestionController.java
  src/main/java/com/umc7th/a1grade/domain/question/controller/QuestionStorageController.java
  src/main/java/com/umc7th/a1grade/global/s3/controller/S3Controller.java
  src/main/java/com/umc7th/a1grade/global/s3/converter/S3Converter.java
  src/main/java/com/umc7th/a1grade/global/s3/dto/S3ResponseDTO.java
  src/main/java/com/umc7th/a1grade/global/s3/entity/PathName.java
  src/main/java/com/umc7th/a1grade/global/s3/service/S3Service.java
Labels: ✨ Feature

#52 :sparkles: feat: 개별 문제 조회 구현
  src/main/java/com/umc7th/a1grade/domain/question/controller/QuestionController.java
  src/main/java/com/umc7th/a1grade/domain/question/converter/QuestionConverter.java
  src/main/java/com/umc7th/a1grade/domain/question/dto/QuestionResponseDTO.java
  src/main/java/com/umc7th/a1grade/domain/question/exception/status/QuestionErrorStatus.java
  src/main/java/com/umc7th/a1grade/domain/question/repository/QuestionRepository.java
  src/main/java/com/umc7th/a1grade/domain/question/repository/UserQuestionRepository.java
  src/main/java/com/umc7th/a1grade/domain/question/service/QuestionService.java
  src/main/java/com/umc7th/a1grade/domain/question/service/QuestionServiceImpl.java
Labels: ✨ Feature

#61 ✨Feat: Credit 기능 추가
  src/main/java/com/umc7th/a1grade/domain/credit/controller/CreditController.java
  src/main/java/com/umc7th/a1grade/domain/credit/dto/CreditResponse.java
  src/main/java/com/umc7th/a1grade/domain/credit/entity/Credit.java
  src/main/java/com/umc7th/a1grade/domain/credit/exception/CreditErrorStatus.java
  src/main/java/com/umc7th/a1grade/domain/credit/repository/CreditRepository.java
  src/main/java/com/umc7th/a1grade/domain/credit/service/CreditService.java
  src/main/java/com/umc7th/a1grade/domain/credit/service/CreditServiceImpl.java
  src/main/java/com/umc7th/a1grade/domain/openAI/controller/OpenAIController.java
  src/main/java/com/umc7th/a1grade/domain/openAI/dto/OpenAIResponse.java
  src/main/java/com/umc7th/a1grade/domain/openAI/infrastructure/GenerateQuestionManager.java
  src/main/java/com/umc7th/a1grade/domain/openAI/service/OpenAIService.java
Labels: ✨ Feature

#72 ♻️ Refactor : 로그아웃 기능 추가 및 토큰 관리 방식 변경
  src/main/java/com/umc7th/a1grade/domain/auth/controller/AuthController.java
  src/main/java/com/umc7th/a1grade/domain/auth/exception/status/AuthErrorStatus.java
  src/main/java/com/umc7th/a1grade/domain/auth/service/GoogleTokenService.java
  src/main/java/com/umc7th/a1grade/domain/auth/service/TokenService.java
  src/main/java/com/umc7th/a1grade/domain/auth/service/TokenServiceImpl.java
  src/main/java/com/umc7th/a1grade/domain/jwt/JwtAuthenticationFilter.java
  src/main/java/com/umc7th/a1grade/domain/jwt/JwtProvider.java
  src/main/java/com/umc7th/a1grade/domain/jwt/JwtProviderImpl.java
  src/main/java/com/umc7th/a1grade/domain/user/entity/User.java
  src/main/java/com/umc7th/a1grade/domain/user/service/UserService.java
  src/main/java/com/umc7th/a1grade/domain/user/service/UserServiceImpl.java
  src/main/java/com/umc7th/a1grade/global/config/SecurityConfig.java
  src/test/java/com/umc7th/a1grade/unittest/auth/fake/FakeJwtProvider.java
  src/test/java/com/umc7th/a1grade/unittest/auth/fake/FakeOAuth2TokenService.java
  src/test/java/com/umc7th/a1grade/unittest/auth/service/GoogleTokenServiceTest.java
  src/test/java/com/umc7th/a1grade/unittest/auth/service/TokenServiceTest.java
  src/test/java/com/umc7th/a1grade/unittest/user/fake/FakeUserRepository.java
Labels: ✨ Feature, 🔨 Refactor

#75 :sparkles:Feat: 사용자 크레딧 기능 추가
  src/main/java/com/umc7th/a1grade/domain/auth/service/GoogleTokenService.java
  src/main/java/com/umc7th/a1grade/domain/user/controller/UserController.java
  src/main/java/com/umc7th/a1grade/domain/user/dto/UserCreditResponseDto.java
  src/main/java/com/umc7th/a1grade/domain/user/entity/User.java
  src/main/java/com/umc7th/a1grade/domain/user/exception/status/UserErrorStatus.java
  src/main/java/com/umc7th/a1grade/domain/user/exception/status/UserSuccessStatus.java
  src/main/java/com/umc7th/a1grade/domain/user/service/UserService.java
  src/main/java/com/umc7th/a1grade/domain/user/service/UserServiceImpl.java
Labels: ✨ Feature

#78 ♻ Refactor : 1등급 경쟁 랭킹 조회 api에 리턴 값 추가
  src/main/java/com/umc7th/a1grade/domain/ranking/service/RankingServiceImpl.java
  src/main/java/com/umc7th/a1grade/domain/user/controller/UserController.java
  src/main/java/com/umc7th/a1grade/domain/user/dto/AllGradeResponseDto.java
  src/main/java/com/umc7th/a1grade/domain/user/dto/UserNicknameResponseDto.java
  src/main/java/com/umc7th/a1grade/domain/user/exception/status/UserSuccessStatus.java
  src/main/java/com/umc7th/a1grade/domain/user/service/UserService.java
  src/main/java/com/umc7th/a1grade/domain/user/service/UserServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#84 :recycle:Refactor: prompt 수식 내용 추가
  src/main/java/com/umc7th/a1grade/domain/openAI/infrastructure/GenerateQuestionManager.java
Labels: 🔨 Refactor

#86 ♻️ Refactor : 랭킹 계산 시 유저 조회 방식 변경
  src/main/java/com/umc7th/a1grade/domain/ranking/service/RankingServiceImpl.java
  src/main/java/com/umc7th/a1grade/domain/user/repository/UserJpaRepository.java
  src/main/java/com/umc7th/a1grade/domain/user/repository/UserRepository.java
  src/main/java/com/umc7th/a1grade/domain/user/repository/UserRepositoryImpl.java
  src/test/java/com/umc7th/a1grade/unittest/user/fake/FakeUserRepository.java
Labels: 🔨 Refactor

#88 🐛 Fix : LazyInitializationException 해결 및 Redis 저장 트랜잭션 처리
  src/main/java/com/umc7th/a1grade/domain/question/repository/QuestionLogRepository.java
  src/main/java/com/umc7th/a1grade/domain/ranking/service/RankingServiceImpl.java
  src/main/java/com/umc7th/a1grade/domain/user/dto/AllGradeResponseDto.java
  src/main/java/com/umc7th/a1grade/domain/user/repository/UserJpaRepository.java
Labels: 🐞 BugFix

#91 ♻️ Refactor : 테스트 계정 로그인 추가
  src/main/java/com/umc7th/a1grade/domain/auth/controller/AuthController.java
  src/main/java/com/umc7th/a1grade/domain/auth/exception/status/AuthErrorStatus.java
  src/main/java/com/umc7th/a1grade/domain/auth/service/GoogleTokenService.java
  src/main/java/com/umc7th/a1grade/domain/auth/service/OAuth2TokenService.java
  src/main/java/com/umc7th/a1grade/domain/user/service/UserServiceImpl.java
  src/test/java/com/umc7th/a1grade/unittest/auth/fake/FakeOAuth2TokenService.java
Labels: ✨ Feature, 🔨 Refactor

#99 ♻️Refactor: prompt 수정
  src/main/java/com/umc7th/a1grade/domain/openAI/infrastructure/GenerateQuestionManager.java
Labels: 🔨 Refactor

#101 :recycle:Refactor: prompt 수정
  src/main/java/com/umc7th/a1grade/domain/openAI/infrastructure/GenerateQuestionManager.java
Labels: 🔨 Refactor
