Repository UMC-7th-A1Grade/BackEnd, pull requests merged in 2025-01, with the labels that each got.

#4 :sparkles:Feat: 응답 통일 코드 구현
  build.gradle
  src/main/java/com/umc7th/a1grade/domain/temp/controller/TempController.java
  src/main/java/com/umc7th/a1grade/domain/temp/converter/TempConverter.java
  src/main/java/com/umc7th/a1grade/domain/temp/dto/TempResponse.java
  src/main/java/com/umc7th/a1grade/domain/temp/handler/TempHandler.java
  src/main/java/com/umc7th/a1grade/domain/temp/handler/status/TempErrorStatus.java
  src/main/java/com/umc7th/a1grade/domain/temp/handler/status/TempSuccessStatus.java
  src/main/java/com/umc7th/a1grade/domain/temp/service/TempQueryService.java
  src/main/java/com/umc7th/a1grade/domain/temp/service/TempQueryServiceImpl.java
  src/main/java/com/umc7th/a1grade/domain/user/exception/status/UserErrorStatus.java
  src/main/java/com/umc7th/a1grade/domain/user/exception/status/UserSuccessStatus.java
  src/main/java/com/umc7th/a1grade/global/apiPayload/ApiResponse.java
  src/main/java/com/umc7th/a1grade/global/apiPayload/code/BaseCode.java
  src/main/java/com/umc7th/a1grade/global/apiPayload/code/BaseErrorCode.java
  src/main/java/com/umc7th/a1grade/global/apiPayload/code/ErrorReasonDTO.java
  src/main/java/com/umc7th/a1grade/global/apiPayload/code/ReasonDTO.java
  src/main/java/com/umc7th/a1grade/global/apiPayload/code/status/CommonErrorStatus.java
  src/main/java/com/umc7th/a1grade/global/apiPayload/code/status/CommonSuccessStatus.java
  src/main/java/com/umc7th/a1grade/global/exception/ExceptionAdvice.java
  src/main/java/com/umc7th/a1grade/global/exception/GeneralException.java
Labels: ✨ Feature

#21 ✨FEAT: JWT Access/Refresh 토큰 생성 및 Google OAuth 인증 로직 수정
  src/main/java/com/umc7th/a1grade/domain/auth/controller/AuthController.java
  src/main/java/com/umc7th/a1grade/domain/auth/dto/GoogleTokenResponse.java
  src/main/java/com/umc7th/a1grade/domain/auth/dto/LoginResponse.java
  src/main/java/com/umc7th/a1grade/domain/auth/dto/OAuthAttributes.java
  src/main/java/com/umc7th/a1grade/domain/auth/exception/AuthHandler.java
  src/main/java/com/umc7th/a1grade/domain/auth/exception/status/AuthErrorStatus.java
  src/main/java/com/umc7th/a1grade/domain/auth/exception/status/AuthSuccessStatus.java
  src/main/java/com/umc7th/a1grade/domain/auth/service/CookieHelper.java
  src/main/java/com/umc7th/a1grade/domain/auth/service/CustomUserDetailsService.java
  src/main/java/com/umc7th/a1grade/domain/auth/service/GoogleTokenService.java
  src/main/java/com/umc7th/a1grade/domain/auth/service/OAuth2TokenService.java
  src/main/java/com/umc7th/a1grade/domain/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/umc7th/a1grade/domain/jwt/JwtFilter.java
  src/main/java/com/umc7th/a1grade/domain/jwt/JwtProvider.java
  src/main/java/com/umc7th/a1grade/domain/jwt/JwtUtil.java
  src/main/java/com/umc7th/a1grade/domain/user/controller/UserController.java
  src/main/java/com/umc7th/a1grade/domain/user/dto/Response.java
  src/main/java/com/umc7th/a1grade/domain/user/dto/UserInfoDto.java
  src/main/java/com/umc7th/a1grade/domain/user/entity/User.java
  src/main/java/com/umc7th/a1grade/domain/user/repository/UserJpaRepository.java
  src/main/java/com/umc7th/a1grade/domain/user/repository/UserRepository.java
  src/main/java/com/umc7th/a1grade/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/umc7th/a1grade/domain/user/service/UserService.java
  src/main/java/com/umc7th/a1grade/domain/user/service/UserServiceImpl.java
  src/main/java/com/umc7th/a1grade/global/config/CorsConfig.java
  src/main/java/com/umc7th/a1grade/global/config/RestTemplateConfig.java
  src/main/java/com/umc7th/a1grade/global/config/SecurityConfig.java
Labels: ⚙ Setting, ✨ Feature

#25 ⚙️ CHORE: Git Action CI/CD workflow 작성
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  Dockerfile
Labels: 🌏 Deploy

#10 ✨ FEAT: 문제 관련 초기 설정 완료 및 컨트롤러 구현
  .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  .github/ISSUE_TEMPLATE/♻️--refactor.md
  .github/ISSUE_TEMPLATE/⚙️-chore.md
  .github/ISSUE_TEMPLATE/✅-test.md
  .github/ISSUE_TEMPLATE/✨-feature.md
  .github/ISSUE_TEMPLATE/🐛-fix.md
  .github/ISSUE_TEMPLATE/📝-documentation.md
  .gitignore
  build.gradle
  src/main/java/com/umc7th/a1grade/domain/question/controller/QuestionController.java
  src/main/java/com/umc7th/a1grade/domain/question/dto/QuestionRequestDTO.java
  src/main/java/com/umc7th/a1grade/domain/question/dto/QuestionResponseDTO.java
  src/main/java/com/umc7th/a1grade/domain/question/entity/Question.java
  src/main/java/com/umc7th/a1grade/domain/question/entity/QuestionType.java
  src/main/java/com/umc7th/a1grade/domain/question/entity/mapping/QuestionLog.java
  src/main/java/com/umc7th/a1grade/domain/question/entity/mapping/UserQuestion.java
  src/main/java/com/umc7th/a1grade/domain/question/exception/status/QuestionErrorStatus.java
  src/main/java/com/umc7th/a1grade/domain/question/repository/QuestionRepository.java
  src/main/java/com/umc7th/a1grade/domain/question/service/QuestionService.java
  src/main/java/com/umc7th/a1grade/domain/question/service/QuestionServiceImpl.java
Labels: ⚙ Setting, ✨ Feature

#39 ♻️Refactor: OpenAI prompt 수정
  build.gradle
  src/main/java/com/umc7th/a1grade/domain/openAI/controller/OpenAIController.java
  src/main/java/com/umc7th/a1grade/domain/openAI/infrastructure/ConfirmQuestionManager.java
  src/main/java/com/umc7th/a1grade/domain/openAI/infrastructure/GenerateQuestionManager.java
Labels: 🔨 Refactor

#48 ♻️Refactor: 예외 명세 및 S3Service 수정
  src/main/java/com/umc7th/a1grade/global/s3/S3Service.java
  src/main/java/com/umc7th/a1grade/global/s3/exception/status/S3ErrorStatus.java
Labels: 🔨 Refactor

#49 ♻️Refactor: 예외 명세 및 Service 수정
  src/main/java/com/umc7th/a1grade/global/s3/S3Service.java
  src/main/java/com/umc7th/a1grade/global/s3/exception/status/S3ErrorStatus.java
Labels: 🔨 Refactor

#53 ✨ FEAT: 저장소 문제 조회 기능 구현
  src/main/java/com/umc7th/a1grade/domain/question/controller/QuestionStorageController.java
  src/main/java/com/umc7th/a1grade/domain/question/converter/QuestionStorageConverter.java
  src/main/java/com/umc7th/a1grade/domain/question/dto/QuestionStorageResponseDTO.java
  src/main/java/com/umc7th/a1grade/domain/question/exception/status/QuestionStorageErrorStatus.java
  src/main/java/com/umc7th/a1grade/domain/question/exception/status/QuestionStorageSuccessStatus.java
  src/main/java/com/umc7th/a1grade/domain/question/repository/UserQuestionRepository.java
  src/main/java/com/umc7th/a1grade/domain/question/service/QuestionStorageService.java
  src/main/java/com/umc7th/a1grade/domain/question/service/QuestionStorageServiceImpl.java
Labels: ✨ Feature
